version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: library
    ports:
      - 5432:5432
  backend:
    build: .
    ports:
      - 8080:8080